logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: localhost # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmdp # 虚拟主机
    username: hmdp # 用户名
    password: hmdp # 密码
    connection-timeout: 1s # 设置MQ的连接超时时间
    # 生产者：重试机制配置（默认不开启）
#    template:
#      retry:
#        enabled: true # 开启超时重试机制
#        initial-interval: 1000ms # 失败后的初始等待时间
#        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
#        max-attempts: 3 # 最大重试次数
    # 生产者：消息确认（ACK）
    publisher-confirm-type: correlated # 确认消息已发送到交换机(Exchange), 异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisher-returns: true # 开启publisher return机制，#确认消息已发送到队列(Queue)